#! /bin/sh

monitor_id_from_name() {
    bspc wm -d | jq ".monitors[] | select(.name == \"$1\").id"
}

MONITOR_CENTER=$(monitor_id_from_name "GPU-0.DVI-I-1");
MONITOR_RIGHT=$(monitor_id_from_name "GPU-0.DVI-D-0");
MONITOR_LEFT=$(monitor_id_from_name "GPU-1.DVI-I-1");

sxhkd &

bspc monitor $MONITOR_CENTER -d 1m 2m 3m & 
bspc monitor $MONITOR_RIGHT -d 1r 2r 3r & 
bspc monitor $MONITOR_LEFT -d 1l 2l 3l & 

#bspc monitor GPU-0.DVI-I-1 -d 1m 2m 3m &
#bspc monitor GPU-0.DVI-D-0 -d 1r 2r 3r &
#bspc monitor GPU-1.DVI-I-0 -d 1l 2l 3l &

#i=1
#for monitor in $(bspc query -M); do
#bspc monitor $monitor \
#        -n "$i" \
#        -d $i/{a,b,c}
#    let i++
#done

$HOME/.config/polybar/launch.sh &

nitrogen --restore &

compton -cb --respect-prop-shadow &

redshift &

pnmixer &

bspc config border_width         1
bspc config window_gap          15
bspc config top_padding		21
bspc config focused_border_color "#e59400"

# insert second window on right instead of left
bspc config initial_polarity second_child

#bspc config pointer_follows_focus 	true
bspc config pointer_follows_monitor 	true

bspc config click_to_focus 	 true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on

# fix java apps, Looking Glass 3D
wmname LG3D
