#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

feh --bg-center /home/cody/Documents/images/backgrounds/business-cat.png

$HOME/.config/polybar/launch.sh

compton -cb --respect-prop-shadow &

redshift &

pnmixer &

bspc config border_width         1
bspc config window_gap          15
bspc config top_padding		21
bspc config focused_border_color "#e59400"

# insert second window on right instead of left
bspc config initial_polarity second_child

#bspc config pointer_follows_focus 	true
#bspc config pointer_follows_monitor 	true

bspc config click_to_focus 	 true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# fix java apps, Looking Glass 3D
wmname LG3D
